import {baseFares, busCost, flightCost, fx, flightLink, weeks, type Party, type Week, type Stay} from './data';

const money=(n:number)=>n.toLocaleString('pl-PL',{maximumFractionDigits:0})+' zł';
export function ownTravelComparison(party:Party,stay:Stay,pass:number):string {
 const rows=(Object.keys(weeks) as Week[]).map(week=>{
  const rent=stay.prices[week];
  return `<tr><th scope="row">${weeks[week].label}</th><td>${rent===null?'Do sprawdzenia':money(rent*fx.eur/party)}</td><td>${money(pass*fx.eur)}</td><td><b>${rent===null?'Niepełna wycena':money(rent*fx.eur/party+pass*fx.eur)}</b></td></tr>`;
 }).join('');
 return `<div id="terminy"><p class="eyebrow">DOJAZD WŁASNY · CENY NA OSOBĘ</p><h2>Porównaj koszt pobytu.</h2><p>${stay.name} · ${party} os. · 7 noclegów + 6 dni wybranego skipassa. Tabela uwzględnia aktualnie wybrany nocleg i skipass.</p><div class="date-table"><table><caption>Pobyt bez kosztów podróży</caption><thead><tr><th>Termin 2027</th><th>Nocleg</th><th>Skipass</th><th>Razem / osoba</th></tr></thead><tbody>${rows}</tbody></table></div><p class="footnote">Koszt dojazdu własnego nie jest wyceniony ani wliczony. Poza sumą także jedzenie, ubezpieczenie i ewentualne dodatki noclegowe. Cennik nie potwierdza dostępności.</p></div>`;
}
export function dateComparison(party:Party):string {
 const rows=(['late','feb','febLate','march'] as Week[]).map(week=>{
  const rent=({late:1150,feb:1790,febLate:1890,march:1050} satisfies Record<Week,number>)[week];
  const total=flightCost(week)+rent*fx.eur/party+421*fx.eur+busCost()*fx.gbp;
  return `<tr><th scope="row"><a href="${flightLink(week,party)}" target="_blank" rel="noopener noreferrer">${weeks[week].label} ↗</a></th><td>${money(baseFares[week])}</td><td>≈ ${money(flightCost(week))}</td><td>${money(rent*fx.eur/party)}</td><td><b>≈ ${money(total+200)}–${money(total+400)}</b></td></tr>`;
 }).join('');
 return `<div id="terminy"><p class="eyebrow">CZTERY TERMINY · ODCZYTY 21–22.09.2026</p><h2>Styczeń, luty czy marzec?</h2><p>Poniżej ceny <b>na osobę przy ${party} dorosłych</b>, za podróż w obie strony i 7 nocy. Porównanie zakłada Pelvoux lub Jettay i pełny skipass 3 Vallées za 421 €. Zmiana noclegu lub skipassa w kalkulatorze powyżej nie zmienia tych założeń.</p><div class="date-table"><table><caption>Sobotnie wyjazdy · ten sam zakres kosztów</caption><thead><tr><th>Termin 2027</th><th>Lot bez dodatków</th><th>Lot z bagażami — szacunek*</th><th>Nocleg · 7 nocy</th><th>Całość — budżet*</th></tr></thead><tbody>${rows}</tbody></table></div><p class="notice"><b>* Bagaż sportowy jest uwzględniony w szacunku, ale opłata dla nowych dat nie jest potwierdzona.</b> Do każdego biletu Wizz doliczamy roboczo 501,44 zł za własny snowboard w obie strony oraz 102,57 zł/os. za ½ walizki 20 kg (jedna walizka na 2 osoby), również w obie strony. Są to stawki odczytane dla wcześniejszego terminu, nie aktualny koszyk wybranych terminów.</p><p class="footnote">Całość obejmuje lot z powyższą rezerwą bagażową, 7 nocy, 6 dni pełnego skipassa, Ben’s Bus według stawki sezonowej z dopłatą bagażową z wcześniejszego sprawdzenia oraz 200–400 zł na kolej i dojazd na Chopina. Bez jedzenia, ubezpieczenia i dodatków noclegowych. Loty 23–30 stycznia i 6–13 lutego odczytano 21.09.2026; loty 20–27 lutego i 6–13 marca oraz cenniki tych noclegów sprawdzono 22.09.2026. Ceny lotów: wynik Skyscannera dla 2 dorosłych, zaokrąglony na osobę; dla większych grup cena może się zmienić. Cennik noclegu nie potwierdza dostępności. Godziny transferu nowych dat wymagają sprawdzenia.</p><p class="notice"><b>Porównanie:</b> 6–13 marca ma najniższy szacowany łączny koszt przy Pelvoux/Jettay dla 2–6 osób. 20–27 lutego ma tani lot, ale najdroższy nocleg z porównywanych terminów.</p></div>`;
}
